import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp(
    home: Abroad_courses(),debugShowCheckedModeBanner: false,
  ));
}
class Abroad_courses extends StatelessWidget {
  final List<String> countries = [
    'UK',
    'CANADA',
    'AUSTRALIA',
    'NEW ZEALAND',
    'GERMANY',
    'FRANCE',
    'IRELAND',
    'ITALY',
    'NEWZEALAND',
    'SPAIN',
  ];
  final Map<String, List<String>> countriesWithCourses = {
    'UK': ['COMPUTER SCIENCE','MBA','INTERNATIONAL BUSSINESS MANAGEMENT','INFORMATION SYSTEMS','BUSINESS ANALYTICS','DATA ANALYTICS','HOTEL MANAGEMENT','BIOMEDICAL','BIOTEC','PUBLIC HEALTH', 'MARKETING', 'DIGITAL MARKETING', 'ADVERTISING', 'BRANDING', 'ENGINEERING MANAGEMENT', 'PROJECT MANAGEMENT', 'CONSTRUCTION MANAGEMENT', 'MECHANICAL ENGINEERING', 'CYBERSECURITY', 'INFORMATION SYSTEM', 'SUPPLY CHAIN', 'HEALTHCARE MANAGEMENT', 'ACCOUNTING', 'FINANCE', 'MANAGEMENT', 'INFORMATION TECHNOLOGY', 'DATA SCIENCE AND ANALYTICS', 'MBA/BUSINESS ADMINISTRATION', 'BIO MED/TECH', 'HEALTHCARE', 'MECHANICAL ENGINEERING', 'MSC CLINICAL PHARMACY', 'MOBILE DEVELOPMENT', 'ELECTRICAL ENGINEERING', 'BUSINESS MANAGEMENT', 'INDUSTRIAL ENGINEERING', 'HR', 'IT', 'HOTEL,TOURISM AND HOSPITALITY MANAGEMENT', 'DESIGN'],
    'CANADA': ['COMPUTER SCIENCE','MBA','INTERNATIONAL BUSSINESS MANAGEMENT','INFORMATION SYSTEMS','BUSINESS ANALYTICS','DATA ANALYTICS','HOTEL MANAGEMENT','BIOMEDICAL','BIOTEC','PUBLIC HEALTH', 'MARKETING', 'DIGITAL MARKETING', 'ADVERTISING', 'BRANDING', 'ENGINEERING MANAGEMENT', 'PROJECT MANAGEMENT', 'CONSTRUCTION MANAGEMENT', 'MECHANICAL ENGINEERING', 'CYBERSECURITY', 'INFORMATION SYSTEM', 'SUPPLY CHAIN', 'HEALTHCARE MANAGEMENT', 'ACCOUNTING', 'FINANCE', 'MANAGEMENT', 'INFORMATION TECHNOLOGY', 'DATA SCIENCE AND ANALYTICS', 'MBA/BUSINESS ADMINISTRATION', 'BIO MED/TECH', 'HEALTHCARE', 'MECHANICAL ENGINEERING', 'MSC CLINICAL PHARMACY', 'MOBILE DEVELOPMENT', 'ELECTRICAL ENGINEERING', 'BUSINESS MANAGEMENT', 'INDUSTRIAL ENGINEERING', 'HR', 'IT', 'HOTEL,TOURISM AND HOSPITALITY MANAGEMENT', 'DESIGN'],
    'AUSTRALIA': ['COMPUTER SCIENCE','MBA','INTERNATIONAL BUSSINESS MANAGEMENT','INFORMATION SYSTEMS','BUSINESS ANALYTICS','DATA ANALYTICS','HOTEL MANAGEMENT','BIOMEDICAL','BIOTEC','PUBLIC HEALTH', 'MARKETING', 'DIGITAL MARKETING', 'ADVERTISING', 'BRANDING', 'ENGINEERING MANAGEMENT', 'PROJECT MANAGEMENT', 'CONSTRUCTION MANAGEMENT', 'MECHANICAL ENGINEERING', 'CYBERSECURITY', 'INFORMATION SYSTEM', 'SUPPLY CHAIN', 'HEALTHCARE MANAGEMENT', 'ACCOUNTING', 'FINANCE', 'MANAGEMENT', 'INFORMATION TECHNOLOGY', 'DATA SCIENCE AND ANALYTICS', 'MBA/BUSINESS ADMINISTRATION', 'BIO MED/TECH', 'HEALTHCARE', 'MECHANICAL ENGINEERING', 'MSC CLINICAL PHARMACY', 'MOBILE DEVELOPMENT', 'ELECTRICAL ENGINEERING', 'BUSINESS MANAGEMENT', 'INDUSTRIAL ENGINEERING', 'HR', 'IT', 'HOTEL,TOURISM AND HOSPITALITY MANAGEMENT', 'DESIGN'],
    'NEW ZEALAND': ['COMPUTER SCIENCE','MBA','INTERNATIONAL BUSSINESS MANAGEMENT','INFORMATION SYSTEMS','BUSINESS ANALYTICS','DATA ANALYTICS','HOTEL MANAGEMENT','BIOMEDICAL','BIOTEC','PUBLIC HEALTH', 'MARKETING', 'DIGITAL MARKETING', 'ADVERTISING', 'BRANDING', 'ENGINEERING MANAGEMENT', 'PROJECT MANAGEMENT', 'CONSTRUCTION MANAGEMENT', 'MECHANICAL ENGINEERING', 'CYBERSECURITY', 'INFORMATION SYSTEM', 'SUPPLY CHAIN', 'HEALTHCARE MANAGEMENT', 'ACCOUNTING', 'FINANCE', 'MANAGEMENT', 'INFORMATION TECHNOLOGY', 'DATA SCIENCE AND ANALYTICS', 'MBA/BUSINESS ADMINISTRATION', 'BIO MED/TECH', 'HEALTHCARE', 'MECHANICAL ENGINEERING', 'MSC CLINICAL PHARMACY', 'MOBILE DEVELOPMENT', 'ELECTRICAL ENGINEERING', 'BUSINESS MANAGEMENT', 'INDUSTRIAL ENGINEERING', 'HR', 'IT', 'HOTEL,TOURISM AND HOSPITALITY MANAGEMENT', 'DESIGN'],
    'GERMANY': ['COMPUTER SCIENCE','MBA','INTERNATIONAL BUSSINESS MANAGEMENT','INFORMATION SYSTEMS','BUSINESS ANALYTICS','DATA ANALYTICS','HOTEL MANAGEMENT','BIOMEDICAL','BIOTEC','PUBLIC HEALTH', 'MARKETING', 'DIGITAL MARKETING', 'ADVERTISING', 'BRANDING', 'ENGINEERING MANAGEMENT', 'PROJECT MANAGEMENT', 'CONSTRUCTION MANAGEMENT', 'MECHANICAL ENGINEERING', 'CYBERSECURITY', 'INFORMATION SYSTEM', 'SUPPLY CHAIN', 'HEALTHCARE MANAGEMENT', 'ACCOUNTING', 'FINANCE', 'MANAGEMENT', 'INFORMATION TECHNOLOGY', 'DATA SCIENCE AND ANALYTICS', 'MBA/BUSINESS ADMINISTRATION', 'BIO MED/TECH', 'HEALTHCARE', 'MECHANICAL ENGINEERING', 'MSC CLINICAL PHARMACY', 'MOBILE DEVELOPMENT', 'ELECTRICAL ENGINEERING', 'BUSINESS MANAGEMENT', 'INDUSTRIAL ENGINEERING', 'HR', 'IT', 'HOTEL,TOURISM AND HOSPITALITY MANAGEMENT', 'DESIGN'],
    'FRANCE': ['COMPUTER SCIENCE','MBA','INTERNATIONAL BUSSINESS MANAGEMENT','INFORMATION SYSTEMS','BUSINESS ANALYTICS','DATA ANALYTICS','HOTEL MANAGEMENT','BIOMEDICAL','BIOTEC','PUBLIC HEALTH', 'MARKETING', 'DIGITAL MARKETING', 'ADVERTISING', 'BRANDING', 'ENGINEERING MANAGEMENT', 'PROJECT MANAGEMENT', 'CONSTRUCTION MANAGEMENT', 'MECHANICAL ENGINEERING', 'CYBERSECURITY', 'INFORMATION SYSTEM', 'SUPPLY CHAIN', 'HEALTHCARE MANAGEMENT', 'ACCOUNTING', 'FINANCE', 'MANAGEMENT', 'INFORMATION TECHNOLOGY', 'DATA SCIENCE AND ANALYTICS', 'MBA/BUSINESS ADMINISTRATION', 'BIO MED/TECH', 'HEALTHCARE', 'MECHANICAL ENGINEERING', 'MSC CLINICAL PHARMACY', 'MOBILE DEVELOPMENT', 'ELECTRICAL ENGINEERING', 'BUSINESS MANAGEMENT', 'INDUSTRIAL ENGINEERING', 'HR', 'IT', 'HOTEL,TOURISM AND HOSPITALITY MANAGEMENT', 'DESIGN'],
    'IRELAND':['COMPUTER SCIENCE','MBA','INTERNATIONAL BUSSINESS MANAGEMENT','INFORMATION SYSTEMS','BUSINESS ANALYTICS','DATA ANALYTICS','HOTEL MANAGEMENT','BIOMEDICAL','BIOTEC','PUBLIC HEALTH', 'MARKETING', 'DIGITAL MARKETING', 'ADVERTISING', 'BRANDING', 'ENGINEERING MANAGEMENT', 'PROJECT MANAGEMENT', 'CONSTRUCTION MANAGEMENT', 'MECHANICAL ENGINEERING', 'CYBERSECURITY', 'INFORMATION SYSTEM', 'SUPPLY CHAIN', 'HEALTHCARE MANAGEMENT', 'ACCOUNTING', 'FINANCE', 'MANAGEMENT', 'INFORMATION TECHNOLOGY', 'DATA SCIENCE AND ANALYTICS', 'MBA/BUSINESS ADMINISTRATION', 'BIO MED/TECH', 'HEALTHCARE', 'MECHANICAL ENGINEERING', 'MSC CLINICAL PHARMACY', 'MOBILE DEVELOPMENT', 'ELECTRICAL ENGINEERING', 'BUSINESS MANAGEMENT', 'INDUSTRIAL ENGINEERING', 'HR', 'IT', 'HOTEL,TOURISM AND HOSPITALITY MANAGEMENT', 'DESIGN'],
    'ITALY': ['COMPUTER SCIENCE','MBA','INTERNATIONAL BUSSINESS MANAGEMENT','INFORMATION SYSTEMS','BUSINESS ANALYTICS','DATA ANALYTICS','HOTEL MANAGEMENT','BIOMEDICAL','BIOTEC','PUBLIC HEALTH', 'MARKETING', 'DIGITAL MARKETING', 'ADVERTISING', 'BRANDING', 'ENGINEERING MANAGEMENT', 'PROJECT MANAGEMENT', 'CONSTRUCTION MANAGEMENT', 'MECHANICAL ENGINEERING', 'CYBERSECURITY', 'INFORMATION SYSTEM', 'SUPPLY CHAIN', 'HEALTHCARE MANAGEMENT', 'ACCOUNTING', 'FINANCE', 'MANAGEMENT', 'INFORMATION TECHNOLOGY', 'DATA SCIENCE AND ANALYTICS', 'MBA/BUSINESS ADMINISTRATION', 'BIO MED/TECH', 'HEALTHCARE', 'MECHANICAL ENGINEERING', 'MSC CLINICAL PHARMACY', 'MOBILE DEVELOPMENT', 'ELECTRICAL ENGINEERING', 'BUSINESS MANAGEMENT', 'INDUSTRIAL ENGINEERING', 'HR', 'IT', 'HOTEL,TOURISM AND HOSPITALITY MANAGEMENT', 'DESIGN'],
    'NEWZEALAND': ['COMPUTER SCIENCE','MBA','INTERNATIONAL BUSSINESS MANAGEMENT','INFORMATION SYSTEMS','BUSINESS ANALYTICS','DATA ANALYTICS','HOTEL MANAGEMENT','BIOMEDICAL','BIOTEC','PUBLIC HEALTH', 'MARKETING', 'DIGITAL MARKETING', 'ADVERTISING', 'BRANDING', 'ENGINEERING MANAGEMENT', 'PROJECT MANAGEMENT', 'CONSTRUCTION MANAGEMENT', 'MECHANICAL ENGINEERING', 'CYBERSECURITY', 'INFORMATION SYSTEM', 'SUPPLY CHAIN', 'HEALTHCARE MANAGEMENT', 'ACCOUNTING', 'FINANCE', 'MANAGEMENT', 'INFORMATION TECHNOLOGY', 'DATA SCIENCE AND ANALYTICS', 'MBA/BUSINESS ADMINISTRATION', 'BIO MED/TECH', 'HEALTHCARE', 'MECHANICAL ENGINEERING', 'MSC CLINICAL PHARMACY', 'MOBILE DEVELOPMENT', 'ELECTRICAL ENGINEERING', 'BUSINESS MANAGEMENT', 'INDUSTRIAL ENGINEERING', 'HR', 'IT', 'HOTEL,TOURISM AND HOSPITALITY MANAGEMENT', 'DESIGN'],
    'SPAIN': ['COMPUTER SCIENCE','MBA','INTERNATIONAL BUSSINESS MANAGEMENT','INFORMATION SYSTEMS','BUSINESS ANALYTICS','DATA ANALYTICS','HOTEL MANAGEMENT','BIOMEDICAL','BIOTEC','PUBLIC HEALTH', 'MARKETING', 'DIGITAL MARKETING', 'ADVERTISING', 'BRANDING', 'ENGINEERING MANAGEMENT', 'PROJECT MANAGEMENT', 'CONSTRUCTION MANAGEMENT', 'MECHANICAL ENGINEERING', 'CYBERSECURITY', 'INFORMATION SYSTEM', 'SUPPLY CHAIN', 'HEALTHCARE MANAGEMENT', 'ACCOUNTING', 'FINANCE', 'MANAGEMENT', 'INFORMATION TECHNOLOGY', 'DATA SCIENCE AND ANALYTICS', 'MBA/BUSINESS ADMINISTRATION', 'BIO MED/TECH', 'HEALTHCARE', 'MECHANICAL ENGINEERING', 'MSC CLINICAL PHARMACY', 'MOBILE DEVELOPMENT', 'ELECTRICAL ENGINEERING', 'BUSINESS MANAGEMENT', 'INDUSTRIAL ENGINEERING', 'HR', 'IT', 'HOTEL,TOURISM AND HOSPITALITY MANAGEMENT', 'DESIGN'],
  };

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Padding(
        padding: const EdgeInsets.all(20.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            const Center(
              child: Text(
                'Expand Your Horizons',
                style: TextStyle(fontSize: 30, fontWeight: FontWeight.bold),
              ),
            ),
            const SizedBox(height: 30),
            Expanded(
              child: ListView.builder(
                itemCount: countries.length,
                itemBuilder: (context, index) {
                  return CountryCoursesTile(
                    country: countries[index],
                    programs: countriesWithCourses[countries[index]]!,
                  );
                },
              ),
            ),
          ],
        ),
      ),
    );
  }
}
class CountryCoursesTile extends StatelessWidget {
  final String country;
  final List<String> programs;

  CountryCoursesTile({required this.country, required this.programs});
  @override
  Widget build(BuildContext context) {
    return Card(
      elevation: 3,
      margin: const EdgeInsets.symmetric(vertical: 10),
      child: Padding(
        padding: const EdgeInsets.all(15),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              'Country: $country',
              style: const TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
            ),
            const SizedBox(height: 10),
            const Text(
              'programs:',
              style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold),
            ),
            const SizedBox(height: 5),
            Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: programs
                  .map((course) => Text(
                '- $course',
                style: const TextStyle(fontSize: 14),
              ))
                  .toList(),
            ),
          ],
        ),
      ),
    );
  }
}